checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - tests/*
build:
    tests:
        override:
            -
                command: ./vendor/bin/phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover