name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  phpcs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP environment
      uses: shivammathur/setup-php@v2
      with:
          php-version: '7.1'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: PHPCSFixer check
      run: composer check-style

  phpstan:
      runs-on: ubuntu-18.04
      steps:
          - uses: actions/checkout@v2

          - name: Setup PHP environment
            uses: shivammathur/setup-php@v2
            with:
                php-version: '7.1'

          - name: Install dependencies
            run: composer install --prefer-dist --no-progress

          - name: PHP Static Analysis
            run: composer phpstan

  phpunit:
    strategy:
      matrix:
        php-versions: ['7.1','7.2','7.3']
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: PHPUnit check
      run: ./vendor/bin/phpunit --coverage-text
