name: tests

on:
    push:
        branches: ["4.x"]
    pull_request:
        branches: ["4.x"]

jobs:
    phpunit:
        strategy:
            matrix:
                php-version: [8.0, 8.1, 8.2]
        runs-on: ubuntu-latest
        name: PHP ${{ matrix.php-version }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  coverage: xdebug
            - name: Install dependencies
              run: composer install --prefer-dist --no-interaction
            - name: Run PHPUnit tests
              run: ./vendor/bin/phpunit
